# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
relative_permalinks: true
permalink:           pretty
# Setup
title:               ORDER365
tagline:             'We Believe in Hardwork'
description:         'A reserved app <a href="http://order365.in" target="_blank">ORDER365</a>allows you to order food, water, juice and other services online. Made by <a href="http://order365.in" target="_blank">Team 365</a> with lot of hardwork and dedication.'
url:                 http://order365.in

shorturl:         order365.in
paginate:            5

# About/contact
author:
  name:              Prince Malik
  url:               https://order365.in/
  email:             princemalik243@gmail.com

# Custom vars
version:             1.0.0
